name: syon_ecommerce_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  iconsax: ^0.0.8
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
 
  uses-material-design: true
